/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * bachao.java
 *
 * Created on Aug 20, 2015, 12:54:18 AM
 */

package ApppPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class bachao extends javax.swing.JFrame {

    /** Creates new form bachao */
    public bachao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameB"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Gurunanak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 20, 100, 23);

        jButton2.setText("St.Thomas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 50, 100, 23);

        jButton3.setText("Vivekanand");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(50, 80, 100, 23);

        jButton4.setText("Kabir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(60, 110, 80, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/bc.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 210, 190);

        setSize(new java.awt.Dimension(211, 203));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   JokhadehaiKB frameB = new JokhadehaiKB();
    bachao.this.setVisible(false);
    frameB.setVisible(true);        // For kabir
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 JokhadehaiGR frameB = new JokhadehaiGR();
    bachao.this.setVisible(false);
    frameB.setVisible(true);        // for gurunanak
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  JokhadehaiST frameB = new JokhadehaiST();
    bachao.this.setVisible(false);
    frameB.setVisible(true);        // for st thomas
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 JokhadehaiVK frameB = new JokhadehaiVK();
    bachao.this.setVisible(false);
    frameB.setVisible(true);        // for vivekanand
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bachao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
