/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * button_dabao.java
 *
 * Created on Aug 14, 2015, 8:44:05 AM
 */

package ApppPackage;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class button_dabao extends javax.swing.JFrame {

    /** Creates new form button_dabao */
    public button_dabao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        v1 = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        v6 = new javax.swing.JLabel();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s5 = new javax.swing.JLabel();
        s6 = new javax.swing.JLabel();
        b111 = new javax.swing.JButton();
        b112 = new javax.swing.JButton();
        b113 = new javax.swing.JButton();
        b114 = new javax.swing.JButton();
        b115 = new javax.swing.JButton();
        b116 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pf1 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Voting");
        setIconImages(null);
        setName("frameV"); // NOI18N
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "CAPTAIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(153, 153, 153))); // NOI18N

        c1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c1.setText("CANDIDATE 1");

        c2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c2.setText("CANDIDATE 2");

        c3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c3.setText("CANDIDATE 3");

        c4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c4.setText("CANDIDATE 4");

        c5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c5.setText("CANDIDATE 5");

        c6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c6.setText("CANDIDATE 6");

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b1.setForeground(new java.awt.Color(102, 102, 102));
        b1.setText("Vote");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b2.setForeground(new java.awt.Color(102, 102, 102));
        b2.setText("Vote");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b3.setForeground(new java.awt.Color(102, 102, 102));
        b3.setText("Vote");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(255, 255, 255));
        b4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b4.setForeground(new java.awt.Color(102, 102, 102));
        b4.setText("Vote");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(255, 255, 255));
        b5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b5.setForeground(new java.awt.Color(102, 102, 102));
        b5.setText("Vote");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(255, 255, 255));
        b6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b6.setForeground(new java.awt.Color(102, 102, 102));
        b6.setText("Vote");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(c1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 78, Short.MAX_VALUE)
                        .add(b1))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(c6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 78, Short.MAX_VALUE)
                        .add(b6))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(c5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 78, Short.MAX_VALUE)
                        .add(b5))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(c4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 78, Short.MAX_VALUE)
                        .add(b4))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(c3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 78, Short.MAX_VALUE)
                        .add(b3))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(c2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 78, Short.MAX_VALUE)
                        .add(b2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(c1)
                    .add(b1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(c2)
                    .add(b2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(c3)
                    .add(b3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(c4)
                    .add(b4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(c5)
                    .add(b5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(c6)
                    .add(b6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 302, 325);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "VICE-CAPTAIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(153, 153, 153))); // NOI18N

        v1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v1.setForeground(new java.awt.Color(51, 51, 51));
        v1.setText("CANDIDATE 1");

        v2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v2.setForeground(new java.awt.Color(51, 51, 51));
        v2.setText("CANDIDATE 2");

        v3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v3.setForeground(new java.awt.Color(51, 51, 51));
        v3.setText("CANDIDATE 3");

        v4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v4.setForeground(new java.awt.Color(51, 51, 51));
        v4.setText("CANDIDATE 4");

        v5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v5.setForeground(new java.awt.Color(51, 51, 51));
        v5.setText("CANDIDATE 5");

        v6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        v6.setForeground(new java.awt.Color(51, 51, 51));
        v6.setText("CANDIDATE 6");

        b11.setBackground(new java.awt.Color(204, 204, 204));
        b11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b11.setForeground(new java.awt.Color(102, 102, 102));
        b11.setText("Vote");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b12.setBackground(new java.awt.Color(204, 204, 204));
        b12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b12.setForeground(new java.awt.Color(102, 102, 102));
        b12.setText("Vote");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b13.setBackground(new java.awt.Color(204, 204, 204));
        b13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b13.setForeground(new java.awt.Color(102, 102, 102));
        b13.setText("Vote");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b14.setBackground(new java.awt.Color(204, 204, 204));
        b14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b14.setForeground(new java.awt.Color(102, 102, 102));
        b14.setText("Vote");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b15.setBackground(new java.awt.Color(204, 204, 204));
        b15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b15.setForeground(new java.awt.Color(102, 102, 102));
        b15.setText("Vote");
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b16.setBackground(new java.awt.Color(204, 204, 204));
        b16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b16.setForeground(new java.awt.Color(102, 102, 102));
        b16.setText("Vote");
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(v1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 106, Short.MAX_VALUE)
                        .add(b11))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(v6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 106, Short.MAX_VALUE)
                        .add(b16))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(v5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 106, Short.MAX_VALUE)
                        .add(b15))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(v4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 106, Short.MAX_VALUE)
                        .add(b14))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(v3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 106, Short.MAX_VALUE)
                        .add(b13))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(v2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 106, Short.MAX_VALUE)
                        .add(b12)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(v1)
                    .add(b11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(v2)
                    .add(b12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(v3)
                    .add(b13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(v4)
                    .add(b14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(v5)
                    .add(b15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(v6)
                    .add(b16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(330, 40, 330, 325);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "SPORTS CAPTAIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(153, 153, 153))); // NOI18N

        s1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        s1.setForeground(new java.awt.Color(102, 102, 102));
        s1.setText("CANDIDATE 1");

        s2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        s2.setForeground(new java.awt.Color(102, 102, 102));
        s2.setText("CANDIDATE 2");

        s3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        s3.setForeground(new java.awt.Color(102, 102, 102));
        s3.setText("CANDIDATE 3");

        s4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        s4.setForeground(new java.awt.Color(102, 102, 102));
        s4.setText("CANDIDATE 4");

        s5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        s5.setForeground(new java.awt.Color(102, 102, 102));
        s5.setText("CANDIDATE 5");

        s6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        s6.setForeground(new java.awt.Color(102, 102, 102));
        s6.setText("CANDIDATE 6");

        b111.setBackground(new java.awt.Color(204, 204, 255));
        b111.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b111.setForeground(new java.awt.Color(102, 102, 102));
        b111.setText("Vote");
        b111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b111ActionPerformed(evt);
            }
        });

        b112.setBackground(new java.awt.Color(204, 204, 255));
        b112.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b112.setForeground(new java.awt.Color(102, 102, 102));
        b112.setText("Vote");
        b112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b112ActionPerformed(evt);
            }
        });

        b113.setBackground(new java.awt.Color(204, 204, 255));
        b113.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b113.setForeground(new java.awt.Color(102, 102, 102));
        b113.setText("Vote");
        b113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b113ActionPerformed(evt);
            }
        });

        b114.setBackground(new java.awt.Color(204, 204, 255));
        b114.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b114.setForeground(new java.awt.Color(102, 102, 102));
        b114.setText("Vote");
        b114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b114ActionPerformed(evt);
            }
        });

        b115.setBackground(new java.awt.Color(204, 204, 255));
        b115.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b115.setForeground(new java.awt.Color(102, 102, 102));
        b115.setText("Vote");
        b115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b115ActionPerformed(evt);
            }
        });

        b116.setBackground(new java.awt.Color(204, 204, 255));
        b116.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        b116.setForeground(new java.awt.Color(102, 102, 102));
        b116.setText("Vote");
        b116.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b116ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(s1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 79, Short.MAX_VALUE)
                        .add(b111))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(s6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 79, Short.MAX_VALUE)
                        .add(b116))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(s5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 79, Short.MAX_VALUE)
                        .add(b115))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(s4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 79, Short.MAX_VALUE)
                        .add(b114))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(s3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 79, Short.MAX_VALUE)
                        .add(b113))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(s2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 79, Short.MAX_VALUE)
                        .add(b112)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(s1)
                    .add(b111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(s2)
                    .add(b112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(s3)
                    .add(b113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(s4)
                    .add(b114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(s5)
                    .add(b115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(s6)
                    .add(b116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(678, 40, 303, 325);

        t1.setBackground(new java.awt.Color(204, 204, 204));
        t1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(436, 11, 105, 23);

        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(402, 376, 90, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 405, 971, 13);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("SET");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(465, 501, 80, 23);

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GR", "VK", "ST", "KB" }));
        cb1.setEnabled(false);
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(460, 470, 90, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("SET");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(136, 501, 70, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("SET");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(782, 501, 70, 23);

        jButton5.setText("HOME");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(510, 376, 80, 23);
        getContentPane().add(pf1);
        pf1.setBounds(375, 430, 119, 20);

        jButton6.setText("GO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(548, 429, 70, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/V.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 1010, 560);

        setSize(new java.awt.Dimension(1021, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
String gr=t1.getText(), v=c1.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO Captain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b1.setEnabled(false);
    b2.setEnabled(false);
    b3.setEnabled(false);
    b4.setEnabled(false);
    b5.setEnabled(false);
    b6.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
String gr=t1.getText(), v=c2.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO Captain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b1.setEnabled(false);
    b2.setEnabled(false);
    b3.setEnabled(false);
    b4.setEnabled(false);
    b5.setEnabled(false);
    b6.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
String gr=t1.getText(), v=c3.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO Captain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b1.setEnabled(false);
    b2.setEnabled(false);
    b3.setEnabled(false);
    b4.setEnabled(false);
    b5.setEnabled(false);
    b6.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
String gr=t1.getText(), v=c4.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO Captain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b1.setEnabled(false);
    b2.setEnabled(false);
    b3.setEnabled(false);
    b4.setEnabled(false);
    b5.setEnabled(false);
    b6.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
String gr=t1.getText(), v=c5.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO Captain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b1.setEnabled(false);
    b2.setEnabled(false);
    b3.setEnabled(false);
    b4.setEnabled(false);
    b5.setEnabled(false);
    b6.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
String gr=t1.getText(), v=c6.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO Captain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b1.setEnabled(false);
    b2.setEnabled(false);
    b3.setEnabled(false);
    b4.setEnabled(false);
    b5.setEnabled(false);
    b6.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b6ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
String gr=t1.getText(), v=v1.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO ViceCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b11.setEnabled(false);
    b12.setEnabled(false);
    b13.setEnabled(false);
    b14.setEnabled(false);
    b15.setEnabled(false);
    b16.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
String gr=t1.getText(), v=v2.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO ViceCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b11.setEnabled(false);
    b12.setEnabled(false);
    b13.setEnabled(false);
    b14.setEnabled(false);
    b15.setEnabled(false);
    b16.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
String gr=t1.getText(), v=v3.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO ViceCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b11.setEnabled(false);
    b12.setEnabled(false);
    b13.setEnabled(false);
    b14.setEnabled(false);
    b15.setEnabled(false);
    b16.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
String gr=t1.getText(), v=v4.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO ViceCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b11.setEnabled(false);
    b12.setEnabled(false);
    b13.setEnabled(false);
    b14.setEnabled(false);
    b15.setEnabled(false);
    b16.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
String gr=t1.getText(), v=v5.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO ViceCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b11.setEnabled(false);
    b12.setEnabled(false);
    b13.setEnabled(false);
    b14.setEnabled(false);
    b15.setEnabled(false);
    b16.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
String gr=t1.getText(), v=v6.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO ViceCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b11.setEnabled(false);
    b12.setEnabled(false);
    b13.setEnabled(false);
    b14.setEnabled(false);
    b15.setEnabled(false);
    b16.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b16ActionPerformed

    private void b111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b111ActionPerformed
String gr=t1.getText(), v=s1.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO SportsCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b111.setEnabled(false);
    b112.setEnabled(false);
    b113.setEnabled(false);
    b114.setEnabled(false);
    b115.setEnabled(false);
    b116.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b111ActionPerformed

    private void b112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b112ActionPerformed
String gr=t1.getText(), v=s2.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO SportsCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b111.setEnabled(false);
    b112.setEnabled(false);
    b113.setEnabled(false);
    b114.setEnabled(false);
    b115.setEnabled(false);
    b116.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b112ActionPerformed

    private void b113ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b113ActionPerformed
String gr=t1.getText(), v=s3.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO SportsCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b111.setEnabled(false);
    b112.setEnabled(false);
    b113.setEnabled(false);
    b114.setEnabled(false);
    b115.setEnabled(false);
    b116.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b113ActionPerformed

    private void b114ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b114ActionPerformed
String gr=t1.getText(), v=s4.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO SportsCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b111.setEnabled(false);
    b112.setEnabled(false);
    b113.setEnabled(false);
    b114.setEnabled(false);
    b115.setEnabled(false);
    b116.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b114ActionPerformed

    private void b115ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b115ActionPerformed
String gr=t1.getText(), v=s5.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO SportsCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b111.setEnabled(false);
    b112.setEnabled(false);
    b113.setEnabled(false);
    b114.setEnabled(false);
    b115.setEnabled(false);
    b116.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b115ActionPerformed

    private void b116ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b116ActionPerformed
String gr=t1.getText(), v=s6.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO SportsCaptain VALUES('"+gr+"','"+v+"')";
    stmt.executeUpdate(query);
    JOptionPane.showMessageDialog(this,"");
    b111.setEnabled(false);
    b112.setEnabled(false);
    b113.setEnabled(false);
    b114.setEnabled(false);
    b115.setEnabled(false);
    b116.setEnabled(false);
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_b116ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    t1.setText("");

    b1.setEnabled(true);
    b2.setEnabled(true);
    b3.setEnabled(true);
    b4.setEnabled(true);
    b5.setEnabled(true);
    b6.setEnabled(true);

    b11.setEnabled(true);
    b12.setEnabled(true);
    b13.setEnabled(true);
    b14.setEnabled(true);
    b15.setEnabled(true);
    b16.setEnabled(true);
     
    b111.setEnabled(true);
    b112.setEnabled(true);
    b113.setEnabled(true);
    b114.setEnabled(true);
    b115.setEnabled(true);
    b116.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Object h=cb1.getSelectedItem();
String h1=h.toString();
String nC1="";
        String nC2="";
        String nC3="";
        String nC4="";
        String nC5="";
        String nC6="";
 try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="Select C1, c2, c3, c4, c5, c6 from rvcaptain Where House='"+h1+"';";
    ResultSet rs = stmt.executeQuery(query);
   while(rs.next())
   {
       nC1=rs.getString("C1") ;
       nC2=rs.getString("c2") ;
       nC3=rs.getString("c3") ;
       nC4=rs.getString("c4") ;
       nC5=rs.getString("c5") ;
       nC6=rs.getString("c6") ;

       


   }
    v1.setText(nC1);
       v2.setText(nC2);
       v3.setText(nC3);
       v4.setText(nC4);
       v5.setText(nC5);
       v6.setText(nC6);
    rs.close();
    stmt.close();
    con.close();
    cb1.setVisible(false);
}
catch(Exception e)
{
    e.getMessage();
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Object h=cb1.getSelectedItem();
String h1=h.toString();
String nC1="";
        String nC2="";
        String nC3="";
        String nC4="";
        String nC5="";
        String nC6="";
 try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="Select C1, c2, c3, c4, c5, c6 from rcaptain Where House='"+h1+"';";
    ResultSet rs = stmt.executeQuery(query);
   while(rs.next())
   {
       nC1=rs.getString("C1") ;
       nC2=rs.getString("c2") ;
       nC3=rs.getString("c3") ;
       nC4=rs.getString("c4") ;
       nC5=rs.getString("c5") ;
       nC6=rs.getString("c6") ;




   }
    c1.setText(nC1);
       c2.setText(nC2);
       c3.setText(nC3);
       c4.setText(nC4);
       c5.setText(nC5);
       c6.setText(nC6);
    rs.close();
    stmt.close();
    con.close();
    cb1.setVisible(false);
}
catch(Exception e)
{
    e.getMessage();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Object h=cb1.getSelectedItem();
String h1=h.toString();
String nC1="";
        String nC2="";
        String nC3="";
        String nC4="";
        String nC5="";
        String nC6="";
 try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="Select C1, c2, c3, c4, c5, c6 from rscaptain Where House='"+h1+"';";
    ResultSet rs = stmt.executeQuery(query);
   while(rs.next())
   {
       nC1=rs.getString("C1") ;
       nC2=rs.getString("c2") ;
       nC3=rs.getString("c3") ;
       nC4=rs.getString("c4") ;
       nC5=rs.getString("c5") ;
       nC6=rs.getString("c6") ;




   }
    s1.setText(nC1);
       s2.setText(nC2);
       s3.setText(nC3);
       s4.setText(nC4);
       s5.setText(nC5);
       s6.setText(nC6);
    rs.close();
    stmt.close();
    con.close();
    cb1.setVisible(false);
}
catch(Exception e)
{
    e.getMessage();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Democracy frameD = new Democracy();        // Toward Voting Page
button_dabao.this.setVisible(false);
frameD.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String p=pf1.getText();
if(p.equals("p@$$w0rd"))// TODO add your handling code here:
{
  cb1.setEnabled(true);
  jButton2.setEnabled(true);
  jButton3.setEnabled(true);
  jButton4.setEnabled(true);
}
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new button_dabao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b11;
    private javax.swing.JButton b111;
    private javax.swing.JButton b112;
    private javax.swing.JButton b113;
    private javax.swing.JButton b114;
    private javax.swing.JButton b115;
    private javax.swing.JButton b116;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JTextField t1;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel v5;
    private javax.swing.JLabel v6;
    // End of variables declaration//GEN-END:variables

}
