/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dekhlo.java
 *
 * Created on Aug 19, 2015, 10:32:37 PM
 */

package ApppPackage;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Dekhlo extends javax.swing.JFrame {

    /** Creates new form Dekhlo */
    public Dekhlo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VOTES");
        setName("frameD"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GR.No.", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb1);
        if (tb1.getColumnModel().getColumnCount() > 0) {
            tb1.getColumnModel().getColumn(0).setResizable(false);
            tb1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 181, 275);

        jButton1.setText("Captain");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(225, 85, 90, 23);

        jButton2.setText("ViceCaptain");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(215, 119, 110, 23);

        jButton3.setText("SportsCaptain");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(209, 153, 130, 23);

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(233, 187, 80, 23);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("HOME");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(225, 44, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/D.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 310);

        setSize(new java.awt.Dimension(364, 335));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel model = (DefaultTableModel) tb1.getModel();
String query="Select * from Captain";
try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/voting","root","agnel");
    Statement stmt = (Statement) con.createStatement();
    ResultSet rs = stmt.executeQuery(query);
    while(rs.next())
    {
        String nGrNo =rs.getString("GrNo");
        String nName =rs.getString("Name");
        model.addRow(new Object[]{nGrNo,nName});
    }
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,"error");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 DefaultTableModel model = (DefaultTableModel) tb1.getModel();
String query="Select * from ViceCaptain";
try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/voting","root","agnel");
    Statement stmt = (Statement) con.createStatement();
    ResultSet rs = stmt.executeQuery(query);
    while(rs.next())
    {
        String nGrNo =rs.getString("GrNo");
        String nName =rs.getString("Name");
        model.addRow(new Object[]{nGrNo,nName});
    }
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,"error");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  DefaultTableModel model = (DefaultTableModel) tb1.getModel();
String query="Select * from SportsCaptain";
try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/voting","root","agnel");
    Statement stmt = (Statement) con.createStatement();
    ResultSet rs = stmt.executeQuery(query);
    while(rs.next())
    {
        String nGrNo =rs.getString("GrNo");
        String nName =rs.getString("Name");
        model.addRow(new Object[]{nGrNo,nName});
    }
}
catch(Exception e)
{
    e.getMessage();
    JOptionPane.showMessageDialog(this,"error");
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Dekhlo frameD = new Dekhlo();
Dekhlo.this.setVisible(false);
frameD.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Democracy frameD = new Democracy();        // Toward Voting Page
        Dekhlo.this.setVisible(false);
        frameD.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dekhlo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables

}
