/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Democracy.java
 *
 * Created on Aug 18, 2015, 11:35:49 PM
 */

package ApppPackage;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class Democracy extends javax.swing.JFrame {

    /** Creates new form Democracy */
    public Democracy() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        v = new javax.swing.JButton();
        e = new javax.swing.JButton();
        pf1 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        s = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainPage");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("frameD"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Towards Voting Process");
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 190, 23);

        v.setBackground(new java.awt.Color(204, 204, 204));
        v.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        v.setForeground(new java.awt.Color(51, 51, 51));
        v.setText("Verdict");
        v.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        v.setEnabled(false);
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });
        getContentPane().add(v);
        v.setBounds(70, 90, 80, 23);

        e.setBackground(new java.awt.Color(204, 204, 204));
        e.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e.setForeground(new java.awt.Color(51, 51, 51));
        e.setText("Entries");
        e.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        e.setEnabled(false);
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(60, 120, 101, 23);

        pf1.setEchoChar('H');
        getContentPane().add(pf1);
        pf1.setBounds(10, 50, 97, 20);

        jButton4.setText("GO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(130, 50, 60, 23);

        s.setBackground(new java.awt.Color(204, 204, 204));
        s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        s.setForeground(new java.awt.Color(51, 51, 51));
        s.setText("Setup");
        s.setEnabled(false);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        getContentPane().add(s);
        s.setBounds(70, 150, 80, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/MP.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 220, 210);

        setSize(new java.awt.Dimension(225, 242));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
button_dabao frameV = new button_dabao();        // Toward Voting Page
Democracy.this.setVisible(false);
frameV.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
Verdict frameB = new Verdict();
Democracy.this.setVisible(false);
frameB.setVisible(true);
// TO Verdict Page
    }//GEN-LAST:event_vActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
bachao frameC = new bachao();
Democracy.this.setVisible(false);
frameC.setVisible(true);
//To entry of candidates
    }//GEN-LAST:event_eActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String n=pf1.getText();
        if(n.equals("Singh.harshit98"))
        {
          v.setEnabled(true);
          e.setEnabled(true);
          s.setEnabled(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Check Password");
        }
}//GEN-LAST:event_jButton4ActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost:3306", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query1="Create database VOTING;";// create Database
    stmt.execute(query1);
   
    String query2="Use VOTING;";
    String query3="Create Table Captain(Grno varchar(6) Primary Key NOT NULL ,Name varchar(30));";
    String query4="Create Table ViceCaptain(Grno varchar(6) Primary Key NOT NULL ,Name varchar(30));";
    String query5="Create Table SportsCaptain(Grno varchar(6) Primary Key NOT NULL ,Name varchar(30));";
    String query6="Create Table RCaptain(House varchar(3) Primary Key NOT NULL ,C1 varchar(30),C2 varchar(30),C3 varchar(30),C4 varchar(30),C5 varchar(30),C6 varchar(30));";
    String query7="Create Table RVCaptain(House varchar(3) Primary Key NOT NULL ,C1 varchar(30),C2 varchar(30),C3 varchar(30),C4 varchar(30),C5 varchar(30),C6 varchar(30));";
    String query8="Create Table RSCaptain(House varchar(3) Primary Key NOT NULL ,C1 varchar(30),C2 varchar(30),C3 varchar(30),C4 varchar(30),C5 varchar(30),C6 varchar(30));";

    stmt.execute(query2);
    stmt.execute(query3);
    stmt.execute(query4);
    stmt.execute(query5);
    stmt.execute(query6);
    stmt.execute(query7);
    stmt.execute(query8);
    
    
    JOptionPane.showMessageDialog(this,"Program Ready");
   
    
}
catch(ClassNotFoundException e)
{
    JOptionPane.showMessageDialog(this,"Program Not ready"+e.getMessage());
}       catch (SQLException e) {
    JOptionPane.showMessageDialog(this,"Program Not ready"+e.getMessage());
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this,"Program Not ready"+e.getMessage());
        }
    }//GEN-LAST:event_sActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) 
    {try { 
    UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel"); 
} catch (ClassNotFoundException ex) { 
}       catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (UnsupportedLookAndFeelException ex) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Democracy().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton e;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JButton s;
    private javax.swing.JButton v;
    // End of variables declaration//GEN-END:variables

}
