/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JokhadehaiVK.java
 *
 * Created on Sep 7, 2015, 11:42:39 PM
 */

package ApppPackage;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class JokhadehaiVK extends javax.swing.JFrame {

    /** Creates new form JokhadehaiVK */
    public JokhadehaiVK() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t5 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        t6 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(t5);
        t5.setBounds(33, 170, 131, 31);
        getContentPane().add(t1);
        t1.setBounds(33, 22, 131, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("ViceCAPTAIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(221, 107, 120, 23);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6);
        t6.setBounds(33, 207, 131, 31);
        getContentPane().add(t4);
        t4.setBounds(33, 133, 131, 31);
        getContentPane().add(t2);
        t2.setBounds(33, 59, 131, 31);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("SportsCaptain");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(208, 141, 140, 23);
        getContentPane().add(t3);
        t3.setBounds(33, 96, 131, 31);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("CAPTAIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(238, 73, 90, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(248, 173, 70, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/vk.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 380, 264);

        setSize(new java.awt.Dimension(392, 302));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String c1=t1.getText(), c2=t2.getText(), c3=t3.getText(), c4=t4.getText(), c5=t5.getText(), c6=t6.getText();
try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO RCaptain VALUES('VK','"+c1+"','"+c2+"','"+c3+"','"+c4+"','"+c5+"','"+c6+"')";
    stmt.executeUpdate(query);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String c1=t1.getText(), c2=t2.getText(), c3=t3.getText(), c4=t4.getText(), c5=t5.getText(), c6=t6.getText();
try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO RVCaptain VALUES('VK','"+c1+"','"+c2+"','"+c3+"','"+c4+"','"+c5+"','"+c6+"')";
    stmt.executeUpdate(query);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String c1=t1.getText(), c2=t2.getText(), c3=t3.getText(), c4=t4.getText(), c5=t5.getText(), c6=t6.getText();
try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="INSERT INTO RSCaptain VALUES('VK','"+c1+"','"+c2+"','"+c3+"','"+c4+"','"+c5+"','"+c6+"')";
    stmt.executeUpdate(query);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Democracy frameD = new Democracy();        // Toward Voting Page
        JokhadehaiVK.this.setVisible(false);
        frameD.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JokhadehaiVK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables

}
