/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Verdict.java
 *
 * Created on Aug 18, 2015, 11:42:08 PM
 */

package ApppPackage;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Verdict extends javax.swing.JFrame {

    /** Creates new form Verdict */
    public Verdict() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        lb3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Result");
        setName("frameC"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        t1.setBackground(new java.awt.Color(204, 204, 204));
        t1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        t1.setForeground(new java.awt.Color(51, 51, 51));
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setText("For Captain");
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(33, 51, 152, 27);

        jLabel1.setText("Enter Name Of Candidate");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(141, 11, 150, 14);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(213, 57, 90, 23);

        lb1.setText("Result");
        getContentPane().add(lb1);
        lb1.setBounds(334, 61, 40, 14);

        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(213, 92, 90, 23);

        t2.setBackground(new java.awt.Color(204, 204, 204));
        t2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(51, 51, 51));
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setText("For ViceCaptain");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(33, 86, 152, 27);

        lb2.setText("Result");
        getContentPane().add(lb2);
        lb2.setBounds(334, 96, 40, 14);

        t3.setBackground(new java.awt.Color(204, 204, 204));
        t3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        t3.setForeground(new java.awt.Color(51, 51, 51));
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.setText("For SportsCaptain");
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t3MouseClicked(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(33, 121, 152, 27);

        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(213, 125, 90, 23);

        lb3.setText("Result");
        getContentPane().add(lb3);
        lb3.setBounds(334, 129, 40, 14);

        jButton4.setText("MainPage");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(152, 188, 110, 23);

        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(174, 154, 70, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/VR.PNG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 430, 250);

        setSize(new java.awt.Dimension(440, 273));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String n=t1.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="Select Count(Name) from Captain Where Name='"+n+"';";
    ResultSet rs = stmt.executeQuery(query);
   while(rs.next())
   {
       int nCount=rs.getInt("Count(Name)") ;
       
       lb1.setText(""+nCount);
   }
    rs.close();
    stmt.close();
    con.close();
   
    
        
        
    
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, "Check Spelling");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
t1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_t1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String n=t2.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="Select Count(Name) from ViceCaptain Where Name='"+n+"';";
    ResultSet rs = stmt.executeQuery(query);
   while(rs.next())
   {
       int nCount=rs.getInt("Count(Name)") ;
       
       lb2.setText(""+nCount);
   }
    rs.close();
    stmt.close();
    con.close();
    
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, "Check Spelling");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
t2.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_t2MouseClicked

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MouseClicked
 t3.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_t3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String n=t3.getText();

try
{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost/voting", "root", "agnel");
    java.sql.Statement  stmt=  con.createStatement();
    String query="Select Count(Name) from SportsCaptain Where Name='"+n+"';";
    ResultSet rs = stmt.executeQuery(query);
   while(rs.next())
   {
       int nCount=rs.getInt("Count(Name)") ;
       
       lb3.setText(""+nCount);
   }
    rs.close();
    stmt.close();
    con.close();
    String v=lb3.getText();
    try
    {
        String query1="INSERT INTO SCVerdict VALUES('"+n+"','"+v+"')";
        stmt.execute(query1);
    }
    catch(Exception f)
    {
        
    }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, "Check Spelling");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Democracy frameM = new Democracy();
Verdict.this.setVisible(false);
frameM.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Dekhlo frameM = new Dekhlo();
Verdict.this.setVisible(false);
frameM.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verdict().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables

}
